# 创建一个zero2prod的桥接网络
networks:
  zero2prod:
    driver: bridge

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: always
    ports:
      - '5432:5432'
    environment:
      # 数据库基本信息
      TZ: Asia/Shanghai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsletter
      # 指定数据目录（可选，容器默认也是 /var/lib/postgresql/data）
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # 数据持久化
      - ../postgresql/data/:/var/lib/postgresql/data/
      # 日志持久化（容器内写入 /var/log/postgresql/postgresql.log）
      - ../postgresql/logs/:/var/log/postgresql/
      # 初始化脚本目录：第一次初始化时，所有 .sql/.sh 会按字母顺序执行
      - ../migrations:/docker-entrypoint-initdb.d/:ro  # ro表示只读
      # 自定义主配置文件
      - ./postgresql/conf/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      # 自定义访问控制文件
      - ./postgresql/conf/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    # 使用自定义配置文件启动 Postgres
    command: [
      "postgres",
      "-c", "config_file=/etc/postgresql/postgresql.conf"
    ]
    networks:
      - zero2prod

#  redis:
#    image: redis:7.2.3
#    restart: always
#    container_name: redis7.2.3
#    ports:
#      - '6379:6379'
#    environment:
#      TZ: Asia/Shanghai
#    volumes:
#      - ./redis/conf/redis.conf:/usr/local/redis/config/redis.conf
#      - ./redis/data/:/data/
#      - ./redis/logs/:/logs/
#    command: redis-server /usr/local/redis/config/redis.conf --appendonly yes --requirepass 123456
#    networks:
#      - zero2prod  # 加入 zero2prod 网络

